# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.parallel = true
org.gradle.caching = true

# Project
minecraft_version = 1.21.1
minecraft_version_range = [1.21.1, 1.22)
neo_version = 21.1.248
neo_version_range = [21.1.180,)
loader_version_range = [4,)
parchment_minecraft_version = 1.21.1
parchment_mappings_version = 2024.11.13

# Mod
mod_id = create_enchantment_industry
mod_artifact_id = create-enchantment-industry-legacy
mod_name = Create: Enchantment Industry Legacy
mod_license = MIT
mod_version = 1.5.0
mod_group_id = plus.dragons.createenchantmentindustry
mod_authors = MarbleGateKeeper, LimonBlaze
mod_description = Automatic Enchanting, with Create. Legacy feature set, ported to 1.21.1 NeoForge.
mod_github = https://github.com/EmilDeuOfficial/EnchantmentIndustryLegacy

# Mod Dependencies
create_version = 6.0.10-280
create_version_range = [6.0.10,)
registrate_version = MC1.21-1.3.0+67
ponder_version = 1.0.87+mc1.21.1
flywheel_version = 1.0.6
jei_minecraft_version = 1.21.1
jei_version = 19.21.2.313
