@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package plus.dragons.createenchantmentindustrylegacy.dragonLibLegacy.advancement.critereon;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;
